services:
  java-maven-app:
    image: tishadev/java-maven-app:1.1.0
    ports:
      - 8080:8080
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTRGERS_USER=root
      - POSTRGERS_PASSWORD=my-pwd
